# Generated by Django 5.0.3 on 2024-03-08 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='discription',
            new_name='description',
        ),
    ]
