# Generated by Django 5.0.3 on 2024-03-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_rename_discription_student_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('enrollment', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
