# Generated by Django 5.0.3 on 2024-03-13 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='email',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='enrollment',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='name',
        ),
    ]
