# Generated by Django 5.0.3 on 2024-03-13 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_remove_faculty_email_remove_faculty_enrollment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
